version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nodeline-admin
      POSTGRES_PASSWORD: 415QKbpi7C6E0zFt6ZcD
      POSTGRES_DB: nodeline-box-persistence

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
  
  box:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile (optional if named 'Dockerfile')
    image: box:0.0.1-SNAPSHOT
    extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8111:8080
    volumes:
      - ./logs:/var/logs/box
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/nodeline-box-persistence
      SPRING_PROFILES_ACTIVE: container